autoDiscovery:
  clusterName: ${clusterName}

awsRegion: us-east-1

rbac:
  serviceAccount:
    name: cluster-autoscaler
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1234:role/AmazonEKSClusterAutoscalerRole

image:
  tag: v1.24.0