apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "route53-credentials"
  namespace: cert-manager
spec:
  secretStoreRef:
    name: awssecretsmanager
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: route53-credentials
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: route53-credentials