datadog:
  clusterName: f4b-cluster
  kubeStateMetricsCore:
    enabled: true
  site: datadoghq.com
  apiKeyExistingSecret: datadog-secret
  hostVolumeMountPropagation: HostToContainer
  logLevel: INFO
  leaderElection: true
  tags:
    - "env": "production"
    - "host": "f4b-cluster"
  logs:
    enabled: true
    containerCollectAll: true
  containerExcludeLogs: "name:datadog-agent"
  dogstatsd:
    useHostPort: true
  apm:
    portEnabled: true
clusterAgent:
  replicas: 2
  admissionController:
    enabled: true
    mutateUnlabelled: true
  createPodDisruptionBudget: true
